# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c583f8f42055d5930d49f37b8107899af41d8c5568d4c9898c3fb90fc84f4df491ae47fb54737a0ef694b9ad634acab00f5bf4466419b40814bf7c5d206fddbd

test:
  secret_key_base: 5b6c12d0a8ec753fccc76dec886755c2a2041949e19cdaeb852fb85b52c2de98ce533a30193e8bc8021f3f9d0abadf3996d506163ef53ed3b54cc578c77186c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
